
import 'package:flutter/material.dart';

class StudyPlanScreen extends StatelessWidget {
  final String plan;

  const StudyPlanScreen({
    super.key,
    required this.plan,
  });

  List<String> get planLines => plan
      .split('\n')
      .map((line) => line.trim())
      .where((line) => line.isNotEmpty)
      .toList();

  bool isBreak(String line) =>
      line.toLowerCase().startsWith('break');

  bool isNumberedSession(String line) =>
      RegExp(r'^\d+[\.)]\s').hasMatch(line);

  String cleanNumber(String line) =>
      line.replaceFirst(RegExp(r'^\d+[\.)]\s*'), '');

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final lines = planLines;

    final title = lines.isNotEmpty &&
            lines.first.toUpperCase().contains('STUDY PLAN')
        ? lines.first
        : "Today's Study Plan";

    final contentLines = lines.isNotEmpty &&
            lines.first.toUpperCase().contains('STUDY PLAN')
        ? lines.skip(1).toList()
        : lines;

    final sessions =
        contentLines.where(isNumberedSession).toList();

    final breaks = contentLines.where(isBreak).toList();

    final otherLines = contentLines
        .where((line) =>
            !isNumberedSession(line) && !isBreak(line))
        .toList();

    return Scaffold(
      appBar: AppBar(
        title: const Text('AI Study Plan'),
      ),
      body: ListView(
        padding: const EdgeInsets.all(20),
        children: [
          Container(
            padding: const EdgeInsets.all(22),
            decoration: BoxDecoration(
              gradient: LinearGradient(
                colors: [
                  theme.colorScheme.primary,
                  theme.colorScheme.tertiary,
                ],
                begin: Alignment.topLeft,
                end: Alignment.bottomRight,
              ),
              borderRadius: BorderRadius.circular(20),
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Icon(
                  Icons.auto_awesome,
                  color: Colors.white,
                  size: 32,
                ),
                const SizedBox(height: 14),
                Text(
                  title,
                  style: theme.textTheme.headlineSmall?.copyWith(
                    color: Colors.white,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                const SizedBox(height: 8),
                const Text(
                  'A personalized plan generated by StudyFlow AI',
                  style: TextStyle(color: Colors.white),
                ),
              ],
            ),
          ),

          const SizedBox(height: 24),

          if (sessions.isNotEmpty) ...[
            Text(
              'Study Sessions',
              style: theme.textTheme.titleLarge?.copyWith(
                fontWeight: FontWeight.bold,
              ),
            ),
            const SizedBox(height: 12),

            ...sessions.map((session) {
              final cleaned = cleanNumber(session);
              final parts = cleaned.split('—');
              final subject = parts.first.trim();
              final duration = RegExp(
                r'\d+\s*(?:minutes?|mins?|hours?|hrs?)',
                caseSensitive: false,
              ).firstMatch(cleaned)?.group(0);

              return Card(
                margin: const EdgeInsets.only(bottom: 12),
                child: Padding(
                  padding: const EdgeInsets.all(16),
                  child: Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      CircleAvatar(
                        backgroundColor:
                            theme.colorScheme.primaryContainer,
                        child: Icon(
                          Icons.menu_book_rounded,
                          color: theme.colorScheme.onPrimaryContainer,
                        ),
                      ),
                      const SizedBox(width: 14),
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              subject,
                              style: theme.textTheme.titleMedium
                                  ?.copyWith(
                                fontWeight: FontWeight.bold,
                              ),
                            ),
                            if (parts.length > 1) ...[
                              const SizedBox(height: 5),
                              Text(parts.skip(1).join('—').trim()),
                            ],
                            if (duration != null) ...[
                              const SizedBox(height: 10),
                              Row(
                                children: [
                                  const Icon(
                                    Icons.schedule,
                                    size: 16,
                                  ),
                                  const SizedBox(width: 5),
                                  Text(
                                    duration,
                                    style: theme.textTheme.labelLarge,
                                  ),
                                ],
                              ),
                            ],
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              );
            }),
          ],

          if (breaks.isNotEmpty) ...[
            const SizedBox(height: 12),
            Text(
              'Remember to take breaks',
              style: theme.textTheme.titleLarge?.copyWith(
                fontWeight: FontWeight.bold,
              ),
            ),
            const SizedBox(height: 12),
            ...breaks.map(
              (line) => Card(
                child: ListTile(
                  leading: const Icon(Icons.coffee_outlined),
                  title: Text(line),
                ),
              ),
            ),
          ],

          if (otherLines.isNotEmpty) ...[
            const SizedBox(height: 12),
            Text(
              'AI Recommendations',
              style: theme.textTheme.titleLarge?.copyWith(
                fontWeight: FontWeight.bold,
              ),
            ),
            const SizedBox(height: 12),
            Card(
              child: Padding(
                padding: const EdgeInsets.all(18),
                child: Text(
                  otherLines.join('\n\n'),
                  style: theme.textTheme.bodyLarge?.copyWith(
                    height: 1.6,
                  ),
                ),
              ),
            ),
          ],

          if (sessions.isEmpty && breaks.isEmpty) ...[
            Card(
              child: Padding(
                padding: const EdgeInsets.all(18),
                child: SelectableText(plan),
              ),
            ),
          ],

          const SizedBox(height: 24),
        ],
      ),
    );
  }
}
